AC-4: Was supposed to be Product View
ezpzcoders-llc/ara-cycling-clothing pull request #6
Opened 2023-07-20 20:12 UTC by KevinLaCarrubba

This is going to be a lot.
- Realized i needed a database (sad face)
- Debating/Trying to implement mixpanel for analytics
- Hooked up with firebase and deployed via firebase
- Hooked up LandingPage to db and redux

2023-07-30 15:22 UTC, arfusop commented on components/ProductDisplay/index.tsx
> +import React from 'react'
Just a fyi going forward, you do not need to import react anymore. Any of the hooks, types, whatever, yes those need imports. But explicitly importing `React` is no longer needed as of v17

2023-07-30 15:28 UTC, arfusop requested changes

2023-07-30 15:28 UTC, arfusop commented on components/ProductGallery/index.tsx
> +            {data?.map((data, index) => {
No need for => {} if you are purely returning JSX. the only time to return an object and type out `return` is if you need a scope for javascript variables or logic. This can and should be 

```
{data?.map((data, index) => (
```

2023-07-30 15:28 UTC, arfusop commented on lib/GoogleAnalytics/GoogleAnalytics.tsx
> +const TRACKING_ID = process.env.NEXT_PUBLIC_GA4_TRACKING_ID!
Why is there a ! at the end of the env var?

2023-07-30 15:28 UTC, arfusop commented on views/AboutView/index.tsx
> +                        src={data[2]?.img.src}
So this is fine and all, but the best thing to do is destructure above and give these data points variable names. Ex:

```
const data = useSelector((state: RootState) => state.aboutPage)

const [whateverIndex1Is, whateverIndex2Is] = data
```
Then reference the variables below, instead of doing `data?.[2]` ect.

If there is no data available, show a loader or something like that

2023-07-30 19:01 UTC, KevinLaCarrubba commented on components/ProductDisplay/index.tsx
> +import React from 'react'
This I knew,  just left it when i rafce tabbed by accident.

2023-07-30 19:02 UTC, KevinLaCarrubba commented on components/ProductGallery/index.tsx
> +            {data?.map((data, index) => {
(Y)

2023-07-31 01:51 UTC, arfusop approved these changes

2023-07-31 13:11 UTC, merged